// OCF2 display-interval contract. env-schema.ts and limits.ts depend on each other,
// so this dependency-free module owns the contract and lets both reference it
// without creating a cycle.
export const FRAME_INTERVAL_MS_VALUES = [
  200, 300, 400, 500, 600, 700, 800, 900, 1_000, 2_000,
] as const
export type FrameIntervalMs = (typeof FRAME_INTERVAL_MS_VALUES)[number]

export const FRAME_INTERVAL_MS_MIN = FRAME_INTERVAL_MS_VALUES[0]
export const FRAME_INTERVAL_MS_MAX =
  FRAME_INTERVAL_MS_VALUES[FRAME_INTERVAL_MS_VALUES.length - 1]!
export const FRAME_INTERVAL_MS_STEP = 100

// Relay playback renders frames generated by another sender and cannot re-split them.
// Keep its established cadence independent from generated-display preference defaults.
export const RELAY_PLAYBACK_FRAME_INTERVAL_MS = 1_000
export { RELAY_PLAYBACK_FRAME_INTERVAL_MS as FRAME_INTERVAL_MS_DEFAULT }

// Append-only: narrowing this boot-readable range can make stored preferences
// unreadable and force wipeOnOnline true.
export const LEGACY_FRAME_INTERVAL_MS_MIN = 150
export const LEGACY_FRAME_INTERVAL_MS_MAX = 3_000

export function isFrameIntervalMs(value: unknown): value is FrameIntervalMs {
  return (
    typeof value === "number" &&
    Number.isSafeInteger(value) &&
    (FRAME_INTERVAL_MS_VALUES as readonly number[]).includes(value)
  )
}

export function isBootReadableFrameIntervalMs(value: unknown): value is number {
  return (
    (typeof value === "number" &&
      Number.isSafeInteger(value) &&
      value >= LEGACY_FRAME_INTERVAL_MS_MIN &&
      value <= LEGACY_FRAME_INTERVAL_MS_MAX) ||
    isFrameIntervalMs(value)
  )
}

export function normalizeLegacyFrameIntervalMs(value: number): FrameIntervalMs {
  if (!isBootReadableFrameIntervalMs(value)) {
    throw new RangeError("frameIntervalMs is not boot-readable")
  }

  // The 2,000ms compatible dwell is intentionally separated from the 200–1,000ms
  // effective grid. Normalize historical values to the nearest admitted value;
  // preserve the previous half-up behavior by choosing the larger value on ties.
  let nearest: FrameIntervalMs = FRAME_INTERVAL_MS_VALUES[0]
  for (const candidate of FRAME_INTERVAL_MS_VALUES.slice(1)) {
    const candidateDistance = Math.abs(candidate - value)
    const nearestDistance = Math.abs(nearest - value)
    if (
      candidateDistance < nearestDistance ||
      (candidateDistance === nearestDistance && candidate > nearest)
    ) {
      nearest = candidate
    }
  }
  return nearest
}
