// PQ Worker RPC client.
//
// Secret boundary (frozen):
//   - Never return seeds, expanded secret keys, shared secrets, or derived key bytes
//     outside the Worker.
//   - Only public keys, KEM ciphertexts, signatures, and final encrypted results leave
//     the Worker.
//   - Do not transfer secret buffers (U3). Transfers are limited to public artifacts in
//     exact-length owned ArrayBuffers; extra backing storage from subarrays is prohibited.
//   - RPC implements correlation IDs, pre-send input-length checks, Worker termination
//     on timeout, ignoring late responses, and sanitized errors.
//   - If the Worker is unavailable, fails to start, or crashes in a browser, fail closed
//     with AppError("WORKER_UNAVAILABLE"). Falling back to the main thread is prohibited.
//     Only Node tests (the Vitest Node project) may call the provider directly.
import type {
  EncryptedSecret,
  MlDsaAlgorithm,
  MlKemAlgorithm,
  MlKemMessageEnvelopeV2,
  PqProfileId,
  WireSuite,
} from "@/schemas/domain"
import { AppError, ERROR_CODES, type ErrorCode } from "@/crypto/errors"
import { guardMlKemEnvelopeV2 } from "@/crypto/pq/canonical-cbor"
import {
  DSA_SIZES,
  KEM_SIZES,
  PQ_PROFILES,
  maxEnvelopeCiphertextBytes,
  maxSignedMessageBytes,
} from "@/crypto/pq/profiles"
import {
  ACTIVE_PROFILE,
  assertActiveProfile,
  assertActiveSuite,
  resolveSuite,
  suiteComponents,
} from "@/crypto/pq/suites"
import { keyIdRawBytes } from "@/crypto/pq/wire-bytes"
import { isVaultKey } from "@/crypto/vault/is-vault-key"
import { env } from "@/schemas/env-schema"
import {
  DSA_SEED_BYTES,
  IV_BYTES,
  KEM_SEED_BYTES,
  KEY_ID_PATTERN,
  MAX_PLAINTEXT_BYTES,
  MESSAGE_ID_BYTES,
} from "@/lib/limits"

// Generation: create seeds with the CSPRNG inside the Worker and encrypt them with the
// Vault key before returning them. Build AAD inside the Worker with buildVaultAadV2,
// including publicKeySha256.
export interface GenerateIdentityKeysRequest {
  profile: PqProfileId
  vaultKey: CryptoKey
  identityId: string
  kemKeyId: string
  signingKeyId: string
}

export interface GeneratedIdentityKeys {
  kem: { publicKey: Uint8Array; encryptedSeed: EncryptedSecret }
  signing: { publicKey: Uint8Array; encryptedSeed: EncryptedSecret }
}

// Re-expansion check: decrypt seed → keygen → return public key.
// The caller must require an exact match with the stored public key before use.
export interface PublicKeysFromSeedsRequest {
  vaultKey: CryptoKey
  identityId: string
  kem: {
    algorithm: MlKemAlgorithm
    keyId: string
    encryptedSeed: EncryptedSecret
    storedPublicKey: Uint8Array
  }
  signing: {
    algorithm: MlDsaAlgorithm
    keyId: string
    encryptedSeed: EncryptedSecret
    storedPublicKey: Uint8Array
  }
}

export interface PublicKeysFromSeedsResult {
  kemPublicKey: Uint8Array
  dsaPublicKey: Uint8Array
}

export interface SignWithSeedRequest {
  algorithm: MlDsaAlgorithm
  vaultKey: CryptoKey
  identityId: string
  keyId: string
  encryptedSeed: EncryptedSecret
  storedPublicKey: Uint8Array // Compare with regenerated key; fail closed on mismatch.
  message: Uint8Array // signingTargetBytes(body)
}

export interface VerifyRequest {
  algorithm: MlDsaAlgorithm
  publicKey: Uint8Array
  message: Uint8Array
  signature: Uint8Array
}

// Encryption performs the entire sign-then-encrypt flow inside the Worker in this order:
// validate → signBody → inner CBOR → Encaps → HKDF → AES-GCM(AAD)
// → zeroize shared-secret/AES material → return envelope
export interface EncryptPqMessageRequest {
  suite: WireSuite
  recipientKemKeyId: string
  recipientKemPublicKey: Uint8Array
  plaintext: Uint8Array
  messageId: Uint8Array // 16B from the CSPRNG, generated by the caller.
  createdAt: number
  sign: {
    senderSigningKeyId: string
    algorithm: MlDsaAlgorithm
    vaultKey: CryptoKey
    identityId: string
    encryptedSeed: EncryptedSecret
    storedPublicKey: Uint8Array
  }
}

// Decryption phase 1 returns canonical bytes of the inner SignedMessageV2, not
// plaintext or receipt fields. Those remain private until verification succeeds.
export interface OpenPqEnvelopeRequest {
  envelope: MlKemMessageEnvelopeV2
  recipient: {
    identityId: string
    kemAlgorithm: MlKemAlgorithm
    kemKeyId: string
    encryptedKemSeed: EncryptedSecret
    storedKemPublicKey: Uint8Array
    vaultKey: CryptoKey
  }
}

export interface OpenedPqEnvelope {
  kind: "signed"
  signedMessageBytes: Uint8Array
  senderSigningKeyId: string
  signatureAlgorithm: MlDsaAlgorithm
}

// Decryption phase 2: construct and return plaintext plus authenticated messageId / createdAt
// only after signature verification succeeds. On failure, zeroize inside the Worker and do
// not create any of those properties.
export interface VerifySignedMessageRequest {
  signedMessageBytes: Uint8Array
  senderPublicKey: Uint8Array
  algorithm: MlDsaAlgorithm
}

export type VerifySignedMessageResult =
  | {
      valid: true
      plaintext: Uint8Array
      messageId: Uint8Array
      createdAt: number
    }
  | { valid: false }

export interface PqCryptoClient {
  generateIdentityKeys(req: GenerateIdentityKeysRequest): Promise<GeneratedIdentityKeys>
  publicKeysFromSeeds(req: PublicKeysFromSeedsRequest): Promise<PublicKeysFromSeedsResult>
  signWithSeed(req: SignWithSeedRequest): Promise<Uint8Array>
  verify(req: VerifyRequest): Promise<boolean>
  encryptPqMessage(req: EncryptPqMessageRequest): Promise<MlKemMessageEnvelopeV2>
  openPqEnvelope(req: OpenPqEnvelopeRequest): Promise<OpenedPqEnvelope>
  verifySignedMessage(req: VerifySignedMessageRequest): Promise<VerifySignedMessageResult>
  // Discard in-flight RPCs and terminate the Worker for WipeCoordinator.
  dispose(): void
}

export interface CreatePqCryptoClientOptions {
  // Test seam. When omitted, resolve from env.pqWorkerEnabled and the runtime environment.
  timeoutMs?: number
}

export type PqWorkerOperation =
  | "generateIdentityKeys"
  | "publicKeysFromSeeds"
  | "signWithSeed"
  | "verify"
  | "encryptPqMessage"
  | "openPqEnvelope"
  | "verifySignedMessage"

export interface PqWorkerRpcRequest {
  id: string
  operation: PqWorkerOperation
  payload: unknown
}

export type PqWorkerRpcResponse =
  { id: string; ok: true; value: unknown } | { id: string; ok: false; code: ErrorCode }

interface WorkerRequestMap {
  generateIdentityKeys: GenerateIdentityKeysRequest
  publicKeysFromSeeds: PublicKeysFromSeedsRequest
  signWithSeed: SignWithSeedRequest
  verify: VerifyRequest
  encryptPqMessage: EncryptPqMessageRequest
  openPqEnvelope: OpenPqEnvelopeRequest
  verifySignedMessage: VerifySignedMessageRequest
}

interface WorkerResultMap {
  generateIdentityKeys: GeneratedIdentityKeys
  publicKeysFromSeeds: PublicKeysFromSeedsResult
  signWithSeed: Uint8Array
  verify: boolean
  encryptPqMessage: MlKemMessageEnvelopeV2
  openPqEnvelope: OpenedPqEnvelope
  verifySignedMessage: VerifySignedMessageResult
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null
}

function isBytes(value: unknown, length?: number): value is Uint8Array {
  return (
    ArrayBuffer.isView(value) &&
    Object.prototype.toString.call(value) === "[object Uint8Array]" &&
    (length === undefined || value.byteLength === length)
  )
}

function isSafeNonNegativeInteger(value: unknown): value is number {
  return typeof value === "number" && Number.isSafeInteger(value) && value >= 0
}

function isKeyId(value: unknown): value is string {
  if (typeof value !== "string" || !KEY_ID_PATTERN.test(value)) return false
  try {
    return keyIdRawBytes(value).byteLength === 16
  } catch {
    return false
  }
}

function isEncryptedSecret(value: unknown, seedBytes: number): boolean {
  if (!isRecord(value)) return false
  return isBytes(value["iv"], IV_BYTES) && isBytes(value["ciphertext"], seedBytes + 16)
}

function requestError(operation: PqWorkerOperation): AppError {
  switch (operation) {
    case "openPqEnvelope":
    case "publicKeysFromSeeds":
      return new AppError("DECRYPTION_FAILED")
    case "verify":
    case "verifySignedMessage":
      return new AppError("SIGNATURE_INVALID")
    case "generateIdentityKeys":
    case "signWithSeed":
    case "encryptPqMessage":
      return new AppError("ENCRYPTION_FAILED")
  }
}

function assertActiveDsaAlgorithm(algorithm: MlDsaAlgorithm): void {
  if (algorithm !== PQ_PROFILES[ACTIVE_PROFILE].signature.algorithm) {
    throw new AppError("UNSUPPORTED_ALGORITHM")
  }
}

// Perform the same checks before postMessage in the browser and before processing in the Worker.
export function validatePqWorkerRequest(
  operation: PqWorkerOperation,
  payload: unknown,
): void {
  try {
    if (!isRecord(payload)) throw requestError(operation)
    switch (operation) {
      case "generateIdentityKeys": {
        const profile = payload["profile"]
        if (
          typeof profile !== "string" ||
          !isVaultKey(payload["vaultKey"]) ||
          !isKeyId(payload["identityId"]) ||
          !isKeyId(payload["kemKeyId"]) ||
          !isKeyId(payload["signingKeyId"])
        ) {
          throw requestError(operation)
        }
        assertActiveProfile(profile as never)
        return
      }
      case "publicKeysFromSeeds": {
        const kem = payload["kem"]
        const signing = payload["signing"]
        if (
          !isVaultKey(payload["vaultKey"]) ||
          !isKeyId(payload["identityId"]) ||
          !isRecord(kem) ||
          !isRecord(signing)
        ) {
          throw requestError(operation)
        }
        const kemAlgorithm = kem["algorithm"]
        const dsaAlgorithm = signing["algorithm"]
        if (
          typeof kemAlgorithm !== "string" ||
          typeof dsaAlgorithm !== "string"
        ) {
          throw requestError(operation)
        }
        assertActiveSuite(resolveSuite(kemAlgorithm as never, dsaAlgorithm as never))
        const activeKemAlgorithm = kemAlgorithm as MlKemAlgorithm
        const activeDsaAlgorithm = dsaAlgorithm as MlDsaAlgorithm
        if (
          !isKeyId(kem["keyId"]) ||
          !isEncryptedSecret(kem["encryptedSeed"], KEM_SEED_BYTES) ||
          !isBytes(
            kem["storedPublicKey"],
            KEM_SIZES[activeKemAlgorithm].publicKeyBytes,
          ) ||
          !isKeyId(signing["keyId"]) ||
          !isEncryptedSecret(signing["encryptedSeed"], DSA_SEED_BYTES) ||
          !isBytes(
            signing["storedPublicKey"],
            DSA_SIZES[activeDsaAlgorithm].publicKeyBytes,
          )
        ) {
          throw requestError(operation)
        }
        return
      }
      case "signWithSeed": {
        const algorithm = payload["algorithm"]
        if (typeof algorithm !== "string") {
          throw requestError(operation)
        }
        assertActiveDsaAlgorithm(algorithm as never)
        const activeAlgorithm = algorithm as MlDsaAlgorithm
        if (
          !isVaultKey(payload["vaultKey"]) ||
          !isKeyId(payload["identityId"]) ||
          !isKeyId(payload["keyId"]) ||
          !isEncryptedSecret(payload["encryptedSeed"], DSA_SEED_BYTES) ||
          !isBytes(
            payload["storedPublicKey"],
            DSA_SIZES[activeAlgorithm].publicKeyBytes,
          ) ||
          !isBytes(payload["message"])
        ) {
          throw requestError(operation)
        }
        return
      }
      case "verify": {
        const algorithm = payload["algorithm"]
        if (typeof algorithm !== "string") {
          throw requestError(operation)
        }
        assertActiveDsaAlgorithm(algorithm as never)
        const activeAlgorithm = algorithm as MlDsaAlgorithm
        if (
          !isBytes(
            payload["publicKey"],
            DSA_SIZES[activeAlgorithm].publicKeyBytes,
          ) ||
          !isBytes(payload["message"]) ||
          !isBytes(
            payload["signature"],
            DSA_SIZES[activeAlgorithm].signatureBytes,
          )
        ) {
          throw requestError(operation)
        }
        return
      }
      case "encryptPqMessage": {
        const rawSuite = payload["suite"]
        if (typeof rawSuite !== "string") {
          throw requestError(operation)
        }
        assertActiveSuite(rawSuite as never)
        const suite = rawSuite as WireSuite
        const components = suiteComponents(suite)
        const sign = payload["sign"]
        if (
          !isKeyId(payload["recipientKemKeyId"]) ||
          !isBytes(
            payload["recipientKemPublicKey"],
            KEM_SIZES[components.kem].publicKeyBytes,
          ) ||
          !isBytes(payload["plaintext"]) ||
          (payload["plaintext"] as Uint8Array).byteLength > MAX_PLAINTEXT_BYTES ||
          !isBytes(payload["messageId"], MESSAGE_ID_BYTES) ||
          typeof payload["createdAt"] !== "number" ||
          !Number.isSafeInteger(payload["createdAt"]) ||
          (payload["createdAt"] as number) < 0
        ) {
          throw requestError(operation)
        }
        if (!isRecord(sign) || sign["algorithm"] !== components.signature) {
          throw requestError(operation)
        }
        if (
          !isKeyId(sign["senderSigningKeyId"]) ||
          !isVaultKey(sign["vaultKey"]) ||
          !isKeyId(sign["identityId"]) ||
          !isEncryptedSecret(sign["encryptedSeed"], DSA_SEED_BYTES) ||
          !isBytes(
            sign["storedPublicKey"],
            DSA_SIZES[components.signature].publicKeyBytes,
          )
        ) {
          throw requestError(operation)
        }
        return
      }
      case "openPqEnvelope": {
        const rawEnvelope = payload["envelope"]
        if (!isRecord(rawEnvelope) || typeof rawEnvelope["suite"] !== "string") {
          throw requestError(operation)
        }
        assertActiveSuite(rawEnvelope["suite"] as never)
        const envelope = guardMlKemEnvelopeV2(payload["envelope"])
        const recipient = payload["recipient"]
        if (!isRecord(recipient)) throw requestError(operation)
        const components = suiteComponents(envelope.suite)
        if (
          envelope.ciphertext.byteLength >
            maxEnvelopeCiphertextBytes(envelope.suite) ||
          recipient["kemAlgorithm"] !== components.kem ||
          recipient["kemKeyId"] !== envelope.recipientKemKeyId ||
          !isKeyId(recipient["identityId"]) ||
          !isKeyId(recipient["kemKeyId"]) ||
          !isEncryptedSecret(recipient["encryptedKemSeed"], KEM_SEED_BYTES) ||
          !isBytes(
            recipient["storedKemPublicKey"],
            KEM_SIZES[components.kem].publicKeyBytes,
          ) ||
          !isVaultKey(recipient["vaultKey"])
        ) {
          throw requestError(operation)
        }
        return
      }
      case "verifySignedMessage": {
        const algorithm = payload["algorithm"]
        if (typeof algorithm !== "string") {
          throw requestError(operation)
        }
        assertActiveDsaAlgorithm(algorithm as never)
        const activeAlgorithm = algorithm as MlDsaAlgorithm
        const signedMessageBytes = payload["signedMessageBytes"]
        if (
          !isBytes(signedMessageBytes) ||
          signedMessageBytes.byteLength === 0 ||
          signedMessageBytes.byteLength > maxSignedMessageBytes(activeAlgorithm) ||
          !isBytes(
            payload["senderPublicKey"],
            DSA_SIZES[activeAlgorithm].publicKeyBytes,
          )
        ) {
          throw requestError(operation)
        }
        return
      }
    }
  } catch (error) {
    if (
      error instanceof AppError &&
      (error.code === requestError(operation).code ||
        error.code === "UNSUPPORTED_ALGORITHM")
    ) {
      throw error
    }
    throw requestError(operation)
  }
}

function validateWorkerResult<K extends PqWorkerOperation>(
  operation: K,
  request: WorkerRequestMap[K],
  value: unknown,
): WorkerResultMap[K] {
  try {
    switch (operation) {
      case "generateIdentityKeys": {
        if (!isRecord(value) || !isRecord(value["kem"]) || !isRecord(value["signing"])) {
          throw new TypeError("worker result")
        }
        const profile = PQ_PROFILES[(request as GenerateIdentityKeysRequest).profile]
        if (
          !isBytes(value["kem"]["publicKey"], profile.kem.publicKeyBytes) ||
          !isEncryptedSecret(value["kem"]["encryptedSeed"], KEM_SEED_BYTES) ||
          !isBytes(value["signing"]["publicKey"], profile.signature.publicKeyBytes) ||
          !isEncryptedSecret(value["signing"]["encryptedSeed"], DSA_SEED_BYTES)
        ) {
          throw new TypeError("worker result")
        }
        break
      }
      case "publicKeysFromSeeds": {
        const req = request as PublicKeysFromSeedsRequest
        if (
          !isRecord(value) ||
          !isBytes(value["kemPublicKey"], KEM_SIZES[req.kem.algorithm].publicKeyBytes) ||
          !isBytes(value["dsaPublicKey"], DSA_SIZES[req.signing.algorithm].publicKeyBytes)
        ) {
          throw new TypeError("worker result")
        }
        break
      }
      case "signWithSeed": {
        const req = request as SignWithSeedRequest
        if (!isBytes(value, DSA_SIZES[req.algorithm].signatureBytes)) {
          throw new TypeError("worker result")
        }
        break
      }
      case "verify":
        if (typeof value !== "boolean") throw new TypeError("worker result")
        break
      case "encryptPqMessage": {
        const req = request as EncryptPqMessageRequest
        const envelope = guardMlKemEnvelopeV2(value)
        if (
          envelope.suite !== req.suite ||
          envelope.recipientKemKeyId !== req.recipientKemKeyId
        ) {
          throw new TypeError("worker result")
        }
        break
      }
      case "openPqEnvelope": {
        const req = request as OpenPqEnvelopeRequest
        if (!isRecord(value) || value["kind"] !== "signed") {
          throw new TypeError("worker result")
        }
        const components = suiteComponents(req.envelope.suite)
        if (
          !isBytes(value["signedMessageBytes"]) ||
          !isKeyId(value["senderSigningKeyId"]) ||
          value["signatureAlgorithm"] !== components.signature ||
          "plaintext" in value ||
          "messageId" in value ||
          "createdAt" in value
        ) {
          throw new TypeError("worker result")
        }
        break
      }
      case "verifySignedMessage":
        if (!isRecord(value) || typeof value["valid"] !== "boolean") {
          throw new TypeError("worker result")
        }
        if (
          value["valid"] &&
          (!isBytes(value["plaintext"]) ||
            !isBytes(value["messageId"], MESSAGE_ID_BYTES) ||
            !isSafeNonNegativeInteger(value["createdAt"]) ||
            "signedMessageBytes" in value ||
            "senderSigningKeyId" in value ||
            "signatureAlgorithm" in value)
        ) {
          throw new TypeError("worker result")
        }
        if (
          !value["valid"] &&
          ("plaintext" in value || "messageId" in value || "createdAt" in value)
        ) {
          throw new TypeError("worker result")
        }
        break
    }
    return value as WorkerResultMap[K]
  } catch {
    throw new AppError("WORKER_UNAVAILABLE")
  }
}

type RpcCall = <K extends PqWorkerOperation>(
  operation: K,
  payload: WorkerRequestMap[K],
) => Promise<WorkerResultMap[K]>

function clientFromRpc(call: RpcCall, dispose: () => void): PqCryptoClient {
  return {
    generateIdentityKeys: (request) => call("generateIdentityKeys", request),
    publicKeysFromSeeds: (request) => call("publicKeysFromSeeds", request),
    signWithSeed: (request) => call("signWithSeed", request),
    verify: (request) => call("verify", request),
    encryptPqMessage: (request) => call("encryptPqMessage", request),
    openPqEnvelope: (request) => call("openPqEnvelope", request),
    verifySignedMessage: (request) => call("verifySignedMessage", request),
    dispose,
  }
}

function createInProcessClient(): PqCryptoClient {
  let disposed = false
  let nextId = 0
  const handler = import("@/workers/pq-crypto.worker").then(
    (module) => module.handlePqWorkerRequest,
  )
  const call: RpcCall = async (operation, payload) => {
    if (disposed) throw new AppError("WORKER_UNAVAILABLE")
    validatePqWorkerRequest(operation, payload)
    const id = `node-${nextId++}`
    const response = await (await handler)({ id, operation, payload })
    if (disposed) throw new AppError("WORKER_UNAVAILABLE")
    if (!response.ok) throw new AppError(response.code)
    return validateWorkerResult(operation, payload, response.value)
  }
  return clientFromRpc(call, () => {
    disposed = true
  })
}

interface PendingRpc {
  operation: PqWorkerOperation
  payload: WorkerRequestMap[PqWorkerOperation]
  resolve(value: unknown): void
  reject(error: AppError): void
  timeout: ReturnType<typeof setTimeout>
}

function createBrowserWorkerClient(timeoutMs: number): PqCryptoClient {
  if (!env.pqWorkerEnabled || typeof Worker === "undefined") {
    throw new AppError("WORKER_UNAVAILABLE")
  }
  let worker: Worker
  try {
    worker = new Worker(new URL("../../workers/pq-crypto.worker.ts", import.meta.url), {
      type: "module",
      name: "qr-crypt-pq-crypto",
    })
  } catch {
    throw new AppError("WORKER_UNAVAILABLE")
  }

  let disposed = false
  let nextId = 0
  const pending = new Map<string, PendingRpc>()

  const failAll = (): void => {
    if (!disposed) worker.terminate()
    disposed = true
    for (const entry of pending.values()) {
      clearTimeout(entry.timeout)
      entry.reject(new AppError("WORKER_UNAVAILABLE"))
    }
    pending.clear()
  }

  worker.addEventListener("error", failAll)
  worker.addEventListener("messageerror", failAll)
  worker.addEventListener("message", (event: MessageEvent<unknown>) => {
    const response = event.data
    if (!isRecord(response) || typeof response["id"] !== "string") return
    const entry = pending.get(response["id"])
    if (entry === undefined) return // Late response after timeout/dispose.
    pending.delete(response["id"])
    clearTimeout(entry.timeout)
    if (response["ok"] === true) {
      try {
        entry.resolve(
          validateWorkerResult(entry.operation, entry.payload, response["value"]),
        )
      } catch {
        failAll()
        entry.reject(new AppError("WORKER_UNAVAILABLE"))
      }
      return
    }
    const code = response["code"]
    if (
      response["ok"] === false &&
      typeof code === "string" &&
      (ERROR_CODES as readonly string[]).includes(code)
    ) {
      entry.reject(new AppError(code as ErrorCode))
    } else {
      failAll()
      entry.reject(new AppError("WORKER_UNAVAILABLE"))
    }
  })

  async function call<K extends PqWorkerOperation>(
    operation: K,
    payload: WorkerRequestMap[K],
  ): Promise<WorkerResultMap[K]> {
    if (disposed) return Promise.reject(new AppError("WORKER_UNAVAILABLE"))
    validatePqWorkerRequest(operation, payload)
    const id = `browser-${nextId++}`
    return new Promise<WorkerResultMap[K]>((resolve, reject) => {
      const timeout = setTimeout(failAll, timeoutMs)
      pending.set(id, {
        operation,
        payload: payload as WorkerRequestMap[PqWorkerOperation],
        resolve,
        reject,
        timeout,
      })
      try {
        // Intentionally omit the transfer list because the input contains secrets.
        worker.postMessage({ id, operation, payload } satisfies PqWorkerRpcRequest)
      } catch {
        failAll()
      }
    })
  }
  return clientFromRpc(call, failAll)
}

export function createPqCryptoClient(
  options?: CreatePqCryptoClientOptions,
): PqCryptoClient {
  const timeoutMs = options?.timeoutMs ?? 30_000
  if (!Number.isSafeInteger(timeoutMs) || timeoutMs < 1 || timeoutMs > 300_000) {
    throw new AppError("WORKER_UNAVAILABLE")
  }
  const isNode =
    typeof window === "undefined" &&
    typeof process !== "undefined" &&
    process.versions?.node !== undefined
  return isNode ? createInProcessClient() : createBrowserWorkerClient(timeoutMs)
}
